### PR TITLE
feat: pkg(add go struct tag)

### PR DESCRIPTION
**Pull request by huangch96**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [X] Y 

re https://github.com/KusionStack/KCLVM/issues/198

#### 2. What is the scope of this PR (e.g. component or file name):

kusionstact/kclvm-go/pkg/tools/gen
 

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [X] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [X] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [x] Other

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Peefy — DISMISSED** [review]
Thank you for your contribution. LGTM

**Comment by Peefy** [comment]
> Thank you for your contribution. LGTM

Oh, the test failed.

**Comment by paragon-h** [comment]
> > Thank you for your contribution. LGTM
> 
> Oh, the test failed.
because  the test case can't use "`" inter the  ``, don't test the tag field.
it will return like this pic 
image

**Review by Peefy — APPROVED** [review]
LGTM

**Pull request merged**
